### PR TITLE
Add a way to force 'false' boolean output when encoding JSON

### PR DESCRIPTION
**Pull request by rpgoldman**

### CODE REVIEW

**Comment by rpgoldman** [comment]
@kierangrant If you are still interested in this, do you have any thoughts about how to test it?

Also, would you please rebase this onto `sharplispers:master` so that we can engage the unit tests on your branch?

**Comment by kierangrant** [comment]
:( I ended up nuking my fork on github as I couldn't get it to update properly to this repo...

Only to realise I was git pushing to my gitlab clone instead of github... :roll_eyes: 

https://github.com/kierangrant/cl-json/tree/add-json-false

Has that original proposed changed rebased off this repo

**Comment by kierangrant** [comment]
I would imagine for testing to make a simple test case of converting to JSON a simple object which references the +JSON-FALSE+ symbol. (or maybe it can be renamed to just FALSE)...

I have been using it for a long time for https://github.com/kierangrant/cl-xplan-api as I need to be able to send the correct JSON false value for that system integration.

**Comment by rpgoldman** [comment]
I poked around some more in the source for cl-json, which I haven't been working with for a while.  I noticed that cl-json already has `json-bool`, where `(json-bool nil)` returns `(:false)`.

So I'm not sure we actually need this patch. Or am I missing something?

**Comment by kierangrant** [comment]
The problem is that I need to encode the value `false` as a bool, and even with this function it doesn't seem to do what I want.

I use `json:encode-json-to-string` and that function is not designed for it.

The documentation for `json-bool` says:

> Intended for the JSON-EXPLICT-ENCODER. Converts a non-nil value to a value (:true) that creates a json true value when used in the explict encoder. Or (:false).

For my use case, when I use T for True, like this example snippet
`(format t "~A~%" (json:encode-json-to-string '((:foo . T))))`

I get the output:
> {"foo":true}

I need to be able to generate an output like so:
> {"foo":false}

Which I couldn't get to work with `json:json-bool`.

**Comment by rpgoldman** [comment]
OK, I understand now. Should we reopen this PR?

Or... I guess this should stay closed and you should open a new one for the correct repo.  Please do that!

**Comment by kierangrant** [comment]
Hmm, now that I think about it, would it be better to perhaps just make the keyword `:false` convert to the JSON `false` value instead of a new symbol like `+JSON-FALSE+`?

So instead just add `("false" . :false)` to the end of `+json-lisp-symbol-tokens+` instead...

I did a very quick test json:encode-to-string and json:decode-from-string as follows with that change:
```lisp
(json:encode-json-to-string '((:foo . :false)))
-> "{\"foo\":false}"
(json:decode-json-from-string "{\"foo\": false\}")
-> ((:FOO))
```

So it could accept `:false` to output to a literal `false` value and still convert from string to `NIL` as before...

Can you think of any good reason to not convert the keyword `:false` to JSON `false` value?

**Comment by rpgoldman** [comment]
`:false` would be fine.  I guess the only question would be if someone is using that in some existing lisp data structure.

In case that could happen, we could have a dynamic variable, `*JSON-FALSE*` that would default to `:false`, but could be rebound to any symbol the programmer likes.

I'd welcome such a PR.

**Pull request closed without merging**
